spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: sxyq1w2e3

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.learn.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl